name: GitHub-Actions-Basics

on:
  push:
    branches:
      - main
      
jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
     - name: Print Hello Message
       run: echo "Hello, World from testing"
       
     - name: Execute few commands
       run: |
          echo "Hello message1"
          echo "Hello message1"
          echo "Application name is ${{ env.APPLICATION_NAME }}"
          
     - name: Execute pwd Command
       run: pwd
       
     - name: Execute ls Command
       run: ls
       
     - name: Checkout code
       uses: actions/checkout@v3
       
     - name: Execute ls Command
       run: ls
       
     - name: Viewing Docker Version 
       run: sudo docker --version
     
     - name: Viewing Docker Images 
       run: sudo docker images 
     
     - name: Viewing Docker Containers 
       run: sudo docker ps
       
     - name: Pull MySQL Image and run container
       run: sudo docker pull mysql 
      
     - name: Run MySQL Container 
       run: sudo docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql      
       
     - name: Viewing Docker Containers 
       run: sudo docker ps
       
     - name: Viewing Python Version
       run: python --version
       
  my-deploy:
    runs-on: ubuntu-latest   
    needs: my-testing
    steps:
     - name: Print Hello Message
       run: echo "Hello, World from deploy"        
          
