name: GitHub-Actions-Basics

env:
  APPLICATION_NAME: "Flask Web App"
  PACKAGE_NAME: "flask-deploy-${{ github.sha }}"
  
on:
  push:
    branches:
      - main
      
jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
     - name: Print Hello Message
       run: echo "Hello, World from testing"
       
     - name: Execute few commands
       run: |
          echo "Hello message1"
          echo "Hello message1"
          echo "Application name is ${{ env.APPLICATION_NAME }}"
          
     - name: Execute pwd Command
       run: pwd
       
     - name: Execute ls Command
       run: ls
       
     - name: Checkout code
       uses: actions/checkout@v3
       
     - name: Execute ls Command
       run: ls
       
     - name: Viewing Docker Version 
       run: sudo docker --version
     
     - name: Viewing Docker Images 
       run: sudo docker images 
     
     - name: Viewing Docker Containers 
       run: sudo docker ps
       
     - name: Pull MySQL Image and run container
       run: | 
          sudo docker pull mysql 
          sudo docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -d mysql
          
  my-deploy:
    runs-on: ubuntu-latest   
    needs: my-testing
    steps:
     - name: Print Hello Message
       run: echo "Hello, World from deploy"
    
     - name: Printing Deployment Package
       run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
          
        
          
